api/urls.py
from django.urls import include, path
from drf_yasg import openapi
from drf_yasg.views import get_schema_view

from . import views

app_name = "api"

schema_view = get_schema_view(
    openapi.Info(
        title="BigCorp API ",
        default_version="v1",
        description="BigCorp API description",
        terms_of_service="https://example.com/terms/",
        contact=openapi.Contact(email="admin@bigcorp.com"),
        license=openapi.License(name="MIT License"),
    ),
    public=True,
)

urlpatterns = [
    # Products
    path("products/", views.ProductListApiView.as_view()),
    path("products/<int:pk>/", views.ProductDetailAPIView.as_view()),
    # Reviews
    path('reviews/create/', views.ReviewCreateView.as_view()),
    # User
    path('auth/', include('djoser.urls')),
    path('auth/', include('djoser.urls.jwt')),
    # Docs
    path('swagger/', schema_view.with_ui('swagger',
         cache_timeout=0), name='schema-swagger-ui'),
    path('redoc/', schema_view.with_ui('redoc',
         cache_timeout=0), name='schema-redoc'),
]

content/urls.py
from django.urls import path
from .views import index, about, article_list

app_name = 'content'

urlpatterns = [
    path('', index, name='content'),
    path('about/', about, name='about'),
    path('articles/', article_list , name='article-list'),
]

main/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django_email_verification import urls as email_urls
from . import views
from django.contrib.sitemaps.views import sitemap
from .sitemaps import ProductSitemap
from django.views.generic import TemplateView


sitemaps = {
    'products': ProductSitemap,
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='sitemap'),
    path("robots.txt", TemplateView.as_view(template_name="robots.txt", content_type="text/plain")),
    path('shop/', include('shop.urls', namespace='shop')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('account/', include('account.urls', namespace='account')),
    path('payment/', include('payment.urls', namespace='payment')),
    path("recommend/", include('recommend.urls', namespace='recommend')),
    path('email/', include(email_urls), name='email-verification'),
    path('api/v1/', include('api.urls', namespace='api')),
    path('content/', include('content.urls', namespace='content')),
    path('', views.index, name='index'),
    path('accounts/', include('django.contrib.auth.urls')),  # Это включает в себя login, logout, управление паролями и т.д.
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

handler404 = 'main.views.handle_404'

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]

if settings.DEBUG:
    
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    
admin.site.site_header = 'Адміністративна панель'
admin.site.index_title = 'Інтернет-магазин "КОМСЕРВІС"'

shop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from .views import *

app_name = 'shop'

urlpatterns = [
    path('', ProductListView.as_view(), name='products'),
    path("search_products/", search_products, name="search-products"),
    path('category/<slug:slug>/', CategoryDetailView.as_view(), name='category-detail'),
    path('price_list/', PriceListView.as_view(), name='price-list'),
    path('download_price_excel/', download_price_excel, name='download-price-excel'),
    path('import_products/', import_products_view, name='import-products'),
    path('product/<slug:slug>/', products_detail_view, name='product-detail'),
    path('sidebar/', sidebar_view, name='sidebar-view'),
    path('brands/', brands_list, name='brands_list'),
    path('brands/<slug:brand_slug>/', brand_products, name='brand_products'),
    path('products/', product_list, name='product_list'),
    path('visit_statistics/', visit_statistics_view, name='visit-statistics'),
   # path('admin/shop/product/update_products_with_api/', update_products_with_api_data, name='update_products_with_api_data'),
] 

content/models.py
from django.db import models

# Create your models here.

class Article(models.Model):
    id = models.AutoField(primary_key=True)
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    content = models.TextField()
    author = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    likes = models.PositiveIntegerField(default=0)
    dislikes = models.PositiveIntegerField(default=0)
    comments = models.PositiveIntegerField(default=0)
    views = models.PositiveIntegerField(default=0)
    image = models.ImageField(null=True, blank=True)
    is_published = models.BooleanField(default=True)

    def get_absolute_url(self):
        return f'/content/{self.id}'
    
    class Meta:
        verbose_name = "Стаття"
        verbose_name_plural = "Статті"

    def __str__(self):
        return self.title

        
        
    

content/views.py
from django.shortcuts import render
from .models import Article

# Create your views here.

def index(request):
    return render(request, 'content/index.html')


def about(request):
    return render(request, 'content/about.html')


def article_list(request):
    articles = Article.objects.filter(is_published=True).order_by('-created_at')
    return render(request, 'content/article_list.html', {'articles': articles})

content/templates/base_cont.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Інтернет магазин "КОМСЕРВІС"</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'shop/css/style.css' %}">
</head>
<body>
    <div class="award">
        Гарячі новинки!!!
    </div>
    <header class="header-top">
        <div class="header-container">
            <a class="navbar-brand">
                <img src= {% static 'images/logo.png' %} alt="Logo" class="logo" />
            </a>
            <nav class="navbar">
                <div class="menu-left">
                    <a class="main-menu-link" href="{% url 'shop:products' %}">SHOP</a>
                    <a class="main-menu-link" href="#">REPAIR</a>
                    <a class="main-menu-link" href="{% url 'content:content' %}">Статті</a>
                    <a class="main-menu-link" href="{% url 'content:about' %}">Про нас</a>
                </div>
            </nav>
            <a class="main-menu-login" href="#">LOGIN</a>
        </div>
    </header>
    <main>
        <!-- Основний контент -->
       
        {% block content %}
        
        {% endblock %}
    </main>
    <footer class="footer">
        <div class="footer-container">
            <div class="footer-section logo-section">
                <img src={% static 'images/logo_dark.png' %} alt="Footer Logo" class="footer-logo" />
                <p>© 2024 Інтернет магазин "КОМСЕРВІС". Усі права захищено.</p>
            </div>
            <div class="footer-section nav-section">
                <a href="/">Головна</a>
                <a href="{% url 'shop:products' %}">Магазин</a>
                <a href="#">Ремонт</a>
                <a href="{% url 'content:content' %}">Новини</a>
                <a href="{% url 'content:about' %}">Контакти</a>
            </div>
            <div class="footer-section contact-section">
                <p>Телефон: +38 (098) 123-45-67</p>
                <p>Email: info@komservis.ua</p>
                <p>Адреса: м. Київ, вул. Технічна, 5</p>
            </div>
        </div>
    </footer>
</html>